################################################################################
# Copyrights © 2021-2025 Fiserv, Inc. or its affiliates.
# Fiserv is a trademark of Fiserv, Inc.,
# registered or used in the United States and foreign countries,
# and may or may not be registered in your country.
# All trademarks, service marks,
# and trade names referenced in this
# material are the property of their
# respective owners. This work, including its contents
# and programming, is confidential and its use
# is strictly limited. This work is furnished only
# for use by duly authorized licensees of Fiserv, Inc.
# or its affiliates, and their designated agents
# or employees responsible for installation or
# operation of the products. Any other use,
# duplication, or dissemination without the
# prior written consent of Fiserv, Inc.
# or its affiliates is strictly prohibited.
# Except as specified by the agreement under
# which the materials are furnished, Fiserv, Inc.
# and its affiliates do not accept any liabilities
# with respect to the information contained herein
# and are not responsible for any direct, indirect,
# special, consequential or exemplary damages
# resulting from the use of this information.
# No warranties, either express or implied,
# are granted or extended by this work or
# the delivery of this work
################################################################################

#openapi: 3.1.0 TODO: gitlab can read 3.0.x
openapi: 3.0.3
info:
  title: index-data openapi spec
  description: Fiserv smalll business readonly index data
  version: '1.0'
servers:
  - {url: 'https://az-p-spring-apps-cert-delivery-ic.private.azuremicroservices.io/index-data/', description: Production}
  - {url: 'https://az-n-spring-verification-app-delivery-ic.private.azuremicroservices.io/index-data/', description: Sandbox}
tags:
  - name: IndexDetail
  - name: DataDownload
paths:
  /api/v1/index-details:
    post:
      tags:
        - IndexDetail
      summary: Search IndexDetails by criteria
      x-proxy-name: index-details
      x-order: 1
      description: Retrieve a list of IndexDetails based on the provided search criteria.
      operationId: searchIndexDetail
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SearchIndexDetailRequest'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/IndexDetailDto'
        400:
          description: 'BAD REQUEST'
          content: {}
        401:
          description: 'UNAUTHORIZED'
          content: {}
        404:
          description: 'NOT FOUND'
          content: {}
        500:
          description: 'INTERNAL SERVER ERROR'
          content: {}
  /api/v1/index-details/adjusted/{example}:
    post:
      tags:
        - IndexDetail
      x-proxy-name: index-details-adjusted-example
      x-order: -1
      summary: Search IndexDetails with adjusted values by criteria
      description: Retrieve a list of IndexDetails with adjusted values based on the provided search criteria.
      operationId: searchIndexDetailAdjusted
      parameters:
        - name: example
          in: path
          required: true
          deprecated: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SearchIndexDetailRequest'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/IndexDetailDto'
        400:
          description: 'BAD REQUEST'
          content: {}
        401:
          description: 'UNAUTHORIZED'
          content: {}
        404:
          description: 'NOT FOUND'
          content: {}
        500:
          description: 'INTERNAL SERVER ERROR'
          content: {}
  /api/v1/index-details/adjusted:
    post:
      tags:
        - IndexDetail
      x-proxy-name: index-details-adjusted
      x-order: 2
      summary: Search IndexDetails with adjusted values by criteria
      description: Retrieve a list of IndexDetails with adjusted values based on the provided search criteria.
      operationId: searchIndexDetailAdjusted
      parameters:
        - name: collection_id
          in: header
          required: true
          deprecated: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SearchIndexDetailRequest'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/IndexDetailDto'
        400:
          description: 'BAD REQUEST'
          content: {}
        401:
          description: 'UNAUTHORIZED'
          content: {}
        404:
          description: 'NOT FOUND'
          content: {}
        500:
          description: 'INTERNAL SERVER ERROR'
          content: {}
  /api/v1/index-details/top-10:
    post:
      tags:
        - IndexDetail
      x-proxy-name: top-10-index-detalis
      x-order: 0
      summary: Top 10 IndexDetails
      description: Retrieve top 10 IndexDetails for last month.
      operationId: getTop10
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TopTenRequest'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/IndexDetailDto'
        400:
          description: 'BAD REQUEST'
          content: {}
        401:
          description: 'UNAUTHORIZED'
          content: {}
        404:
          description: 'NOT FOUND'
          content: {}
        500:
          description: 'INTERNAL SERVER ERROR'
          content: {}
  /api/v1/index-history:
    post:
      tags:
        - IndexHistory
      x-proxy-name: index-history
      summary: Search history by criteria
      description: Retrieve a list of naics3 history records that show index values for them for the last 12 months.
      operationId: searchHistory
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SearchHistoryRequest'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SearchHistoryResponse'
        400:
          description: 'BAD REQUEST'
          content: {}
        401:
          description: 'UNAUTHORIZED'
          content: {}
        404:
          description: 'NOT FOUND'
          content: {}
        500:
          description: 'INTERNAL SERVER ERROR'
          content: {}
  /api/v1/index-history/adjusted:
    post:
      tags:
        - IndexHistory
      x-proxy-name: index-history-adjusted
      x-order: 1
      summary: Search history with adjusted values by criteria
      description: Retrieve a list of naics3 history records with adjusted values that show index values for them for the last 12 months.
      operationId: searchHistoryAdjusted
      deprecated: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SearchHistoryRequest'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SearchHistoryResponse'
        400:
          description: 'BAD REQUEST'
          content: {}
        401:
          description: 'UNAUTHORIZED'
          content: {}
        404:
          description: 'NOT FOUND'
          content: {}
        500:
          description: 'INTERNAL SERVER ERROR'
          content: {}
components:
  schemas:
    DataDownloadRequest:
      type: object
      properties:
        dataSet:
          type: string
          example: 'ALL'
        selectFields:
          type: array
          items:
            type: string
            description: Will have columnNames that will be used for select statement.
          example: ['sales_index', 'count_index', 'mom_percent_chg', 'yoy_percent_chg']
        queryFilter:
          type: object
          properties:
            geo:
              type: array
              items:
                type: string
              description: Optional, geo to be used a filter. If not provided - all known geo codes will be included.
              example: ['US']
            msa:
              type: array
              items:
                type: string
              description: Optional, msa to be used a filter. If not provided - no msa records will be included.
              example: ['12060', '14460', '16980', '19100', '31080', '33100', '35620', '37980', '41860', '47900']
            naicsCode3s:
              type: array
              items:
                type: string
              description: Optional, naicsCode3s to be included in the result. If not provided - all known naics3 will be included.
              example: ['0']
            naicsCode2s:
              type: array
              items:
                type: string
              description: Optional, naicsCode2s to be included in the result. If not provided - all known naics2 will be included.
              example: ['0']
            startPeriod:
              type: string
              format: date
              description: Optional, start period of the query. If not provided the previous month of the current date will be used!
              example: '2025-03-01'
            endPeriod:
              type: string
              format: date
              description: Optional, end period of the query. If not provided the previous month of the current date will be used!
              example: '2025-03-01'
            seasonallyAdjusted:
              type: boolean
              example: 'true'
            nonSeasonallyAdjusted:
              type: boolean
              example: 'true'
    SearchHistoryRequest:
      type: object
      properties:
        geo:
          type: string
          description: Optional, geo to be included in the result. If not provided - all known geo codes will be included.
          example: 'US'
        naicsCode3s:
          type: array
          items:
            type: string
          description: Optional, naicsCode3s to be included in the result. If not provided - all known naics3 will be included.
          example: ['622', '423', '812', '524', '336', '519', '711', '541', '444', '621', '813', '457', '221', '445']
        period:
          type: string
          format: date
          description: Optional, period of the last of 12 moths. If not provided the previous moth of the current date will be used!
          example: '2025-03-01'
        isInflation:
          type: boolean
          default: false
          description: If true, inflation related data will be returned, Else non-inflation data will be returned.
          example: 'false'
          deprecated: true
    MonthIndexValue:
      type: object
      properties:
        salesIndex:
          type: number
          format: double
        countIndex:
          type: number
          format: double
        period:
          type: string
          format: date
    ByNaicsCode3History:
      type: object
      properties:
        naicsCode3:
          type: string
        naicsShortDesc3:
          type: string
        naicsDesc3:
          type: string
        salesMomDiff:
          type: number
          format: double
        salesYoyDiff:
          type: number
          format: double
        countMomDiff:
          type: number
          format: double
        countYoyDiff:
          type: number
          format: double
        volumeRank:
          type: integer
        countIndexChange:
          type: integer
        salesIndexChange:
          type: integer
        monthlyIndexValues:
          type: array
          deprecated: true
          items:
            $ref: '#/components/schemas/MonthIndexValue'
    SearchHistoryResponse:
      type: object
      properties:
        geo:
          type: string
          deprecated: true
        byNaicsCode3:
          type: array
          items:
            $ref: '#/components/schemas/ByNaicsCode3History'
    SearchIndexDetailRequest:
      type: object
      required:
        - startPeriod
      properties:
        naicsCode2:
          type: string
          maxLength: 50
          example: '0'
        naicsCode3:
          type: string
          maxLength: 50
          example: '0'
        geo:
          type: string
          description: geo location
          example: 'US'
        fetchMSA:
          type: boolean
          default: false
          description: fetch stuff if true
          example: 'false'
          deprecated: true
        startPeriod:
          type: string
          format: date
          example: 1990-12-31
        startPeriod1:
          type: string
          format: date
          example: 1999-01-01
        startPeriod2:
          type: string
          format: date
          example: 1900-01-01
        startPeriod3:
          type: string
          format: date
          example: 12-31-01
        startPeriod4:
          type: string
          format: date
          example: 31-12-0001
        startPeriod5:
          type: string
          format: date
          description: the date
          example: 0010-12-31
        startPeriod6:
          type: string
          format: date
          example: 0001-01-01
        startPeriod7:
          type: string
          format: date
          example: 2025-05-30
        startPeriod8:
          type: string
          format: date-time
          example: 2024-12-01T00:00:00.000Z
          deprecated: true
        endPeriod:
          type: string
          format: date-time
          example: 2023-02-16T09:10:27Z
        isInflation:
          type: boolean
          default: false
          example: 'false'
    IndexDetailDto:
      type: object
      properties:
        geo:
          type: string
          maxLength: 2
        geoName:
          type: string
        geoRegion:
          type: string
        naicsCode2:
          type: string
        naicsShortDesc2:
          type: string
        naicsDesc2:
          type: string
        naicsCode3:
          type: string
        naicsShortDesc3:
          type: string
        naicsDesc3:
          type: string
        salesIndex:
          type: number
          format: double
        salesMomDiff:
          type: number
          format: double
        salesMomRank:
          type: integer
        salesYoyDiff:
          type: number
          format: double
        countIndex:
          type: number
          format: double
        countMomDiff:
          type: number
          format: double
        countYoyDiff:
          type: number
          format: double
        period:
          type: string
          format: date
        volumeRank:
          type: integer
        countIndexChange:
          type: integer
        salesIndexChange:
          type: integer
    LastDateResponse:
      type: object
      properties:
        lastDate:
          type: string
    ReportType:
      type: object
      properties:
        code:
          type: string
        value:
          type: string
        isActive:
          type: boolean
    Naics3:
      type: object
      properties:
        naicsCode3:
          type: string
        naicsDesc3:
          type: string
        naicsShortDesc3:
          type: string
    Naics2:
      type: object
      properties:
        naicsCode2:
          type: string
        naicsDesc2:
          type: string
        naicsShortDesc2:
          type: string
    State:
      type: object
      properties:
        state:
          type: string
        name:
          type: string
        region:
          type: string
    Metrics:
      type: object
      properties:
        code:
          type: string
        value:
          type: string
    TopTenRequest:
      type: object
      properties:
        isInflation:
          type: boolean
          default: false
          example: 'false'
