################################################################################
# Copyrights © 2022-2025 Fiserv, Inc. or its affiliates. Fiserv is a trademark of Fiserv, Inc.,
# registered or used in the United States and foreign countries, and may or may not be registered in your country.
# All trademarks, service marks, and trade names referenced in this
# material are the property of their respective owners. This work, including its contents
# and programming, is confidential and its use is strictly limited. This work is furnished only
# for use by duly authorized licensees of Fiserv, Inc. or its affiliates, and their designated agents
# or employees responsible for installation or operation of the products. Any other use,
# duplication, or dissemination without the prior written consent of Fiserv, Inc.
# or its affiliates is strictly prohibited. Except as specified by the agreement under
# which the materials are furnished, Fiserv, Inc. and its affiliates do not accept any liabilities
# with respect to the information contained herein and are not responsible for any direct, indirect,
# special, consequential or exemplary damages resulting from the use of this information.
# No warranties, either express or implied, are granted or extended by this work or
# the delivery of this work.
################################################################################
- sections:
  - title: Overview
    link: SDKs/resources.md
- sections:
  - title: SDKs
    sections:
    - title: SDK documentation 1
      link: SDKs/SDK_1.md
    - title: SDK documentation 2
      link: SDKs/SDK_2.md
    - title: SDK documentation 3
      link: SDKs/SDK_3.md
- sections:
  - title: Developer Studio Test SDK 1
    sections:
    - title: Overview
      link: SDKs/sdk-example-1/sdk-overview-1.mdx
    - title: Code Examples
      sections:
      - title: Fetching from an Endpoint
        link: SDKs/sdk-example-1/code-examples/fetching-from-endpoint.mdx
      - title: Posting to an Endpoint
        link: SDKs/sdk-example-1/code-examples/posting-to-endpoint.mdx
    - title: Version History
      sections:
      - title: v2.0
        link: SDKs/sdk-example-1/version-history/2.0.mdx
      - title: v1.1
        link: SDKs/sdk-example-1/version-history/1.1.mdx
      - title: v1.0
        link: SDKs/sdk-example-1/version-history/1.0.mdx
- sections:
  - title: Developer Studio Test SDK 2
    sections:
    - title: Overview
      link: SDKs/sdk-example-2/sdk-overview-2.mdx
    - title: Getting Started
      link: SDKs/sdk-example-2/getting-started.mdx
    - title: Java
      sections:
      - title: Code Examples
        link: SDKs/sdk-example-2/java/java-code-examples.mdx
    - title: Python
      sections:
      - title: Code Examples
        link: SDKs/sdk-example-2/python/python-code-examples.mdx
