openapi: 3.0.3

info:
  title: Sample API
  version: 1.0.0

paths:
  /customers/{customerId}:
    get:
      summary: Get a customer
      parameters:
        - name: customerId
          in: path
          required: true

          # Parameter-level example
          example: "12345"

          schema:
            type: string

            # Schema-level example
            # example: "67890"

            # Default value (allowed in the schema)
            default: "00000"

      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  customerId:
                    type: string
      x-proxy-name: Get Customer
      x-group-name: Path Param Test

